# Generated by Django 5.2.15 on 2026-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_district_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ngo',
            field=models.BooleanField(default=False, help_text='Designates if this user account is a verified NGO partner'),
        ),
        migrations.AddField(
            model_name='user',
            name='ngo_name',
            field=models.CharField(blank=True, help_text='Name of verified NGO partner organization', max_length=150),
        ),
    ]
