# Generated by Django 5.2.15 on 2026-07-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('estimated_resolution_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_types', to='categories.complaintcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_types', to='departments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('keyword', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('complaint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='knowledge.complainttype')),
            ],
            options={
                'ordering': ['keyword'],
                'unique_together': {('complaint_type', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='RequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('complaint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='knowledge.complainttype')),
            ],
            options={
                'ordering': ['field_name'],
                'unique_together': {('complaint_type', 'field_name')},
            },
        ),
    ]
