"""
models/complaint.py

The central domain object of the AI module: a Complaint as understood
after LLM classification + business-rule processing. This is what
services pass to each other internally — distinct from the API
request/response shapes in schemas/, which are the external contract.

Kept intentionally free of any FastAPI/Pydantic-API concerns (no
HTTP status codes, no request-id, no pagination) — those belong in
schemas/.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from pydantic import BaseModel, Field

from app.models.category import Category
from app.models.department import Department
from app.models.entity import ExtractedEntities
from app.models.enums import ComplaintStatus, Language
from app.models.priority import PriorityAssessment


class ComplaintInput(BaseModel):
    """Raw citizen-submitted complaint, prior to any AI processing.

    This is the minimal, unvalidated-by-business-rules starting point
    that enters the orchestrator. Preprocessing (utils/text.py) may
    clean whitespace/encoding but does not alter meaning.
    """

    raw_text: str = Field(min_length=1, max_length=5000)
    declared_language: Language | None = Field(
        default=None,
        description="Language the citizen selected in the UI, if any. "
        "May differ from the detected language; services decide which "
        "wins per the language-handling policy.",
    )


class Complaint(BaseModel):
    """A fully processed complaint: classified, entity-extracted, and
    prioritized.

    Attributes:
        id: Server-generated identifier for this AI-processing run.
            NOT a database primary key — the Django backend generates
            its own complaint ID upon persistence. This ID exists only
            to correlate logs/retries within the AI service.
        status: Where this complaint is in the AI module's own
            pipeline (see models/enums.ComplaintStatus).
    """

    id: uuid.UUID = Field(default_factory=uuid.uuid4)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    status: ComplaintStatus = ComplaintStatus.RECEIVED

    original_text: str
    detected_language: Language
    translated_text: str | None = Field(
        default=None,
        description="English translation, populated when detected_language "
        "!= English and downstream processing requires it.",
    )

    category: Category | None = None
    department: Department | None = None
    entities: ExtractedEntities | None = None
    priority: PriorityAssessment | None = None

    generated_draft: str | None = Field(
        default=None,
        description="Professional complaint draft generated by the LLM, "
        "reviewed/assembled by draft_service.py.",
    )
    suggested_documents: list[str] = Field(default_factory=list)
    classification_confidence: float | None = Field(
        default=None,
        description="LLM's self-reported confidence in the category "
        "prediction, carried through from classification for the API "
        "response. None until classification has run.",
    )

    def is_ready_for_submission(self) -> bool:
        """Whether this complaint has all fields required to be
        handed off to the Django backend for form submission.
        """
        return all(
            [
                self.category is not None,
                self.department is not None,
                self.priority is not None,
                self.status == ComplaintStatus.READY_FOR_SUBMISSION,
            ]
        )
