# Generated by Django 5.2.15 on 2026-07-08 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_district_is_deleted_district_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('office_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_offices', to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_offices', to='locations.state')),
            ],
            options={
                'verbose_name': 'Department Office',
                'verbose_name_plural': 'Department Offices',
                'ordering': ['office_name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'district', 'office_name'), name='unique_department_office')],
            },
        ),
    ]
