# ai/constants.py
from enum import Enum

class Intent(Enum):
    GREETING = "GREETING"
    FILE_COMPLAINT = "FILE_COMPLAINT"
    TRACK_COMPLAINT = "TRACK_COMPLAINT"
    SEARCH_SCHEME = "SEARCH_SCHEME"
    OFFICE_LOOKUP = "OFFICE_LOOKUP"
    GENERAL_QUERY = "GENERAL_QUERY"
    HELP = "HELP"
    GOODBYE = "GOODBYE"
    CONFIRM = "CONFIRM"
    UNKNOWN = "UNKNOWN"

class NextAction(Enum):
    ASK_COMPLAINT_DETAILS = "ASK_COMPLAINT_DETAILS"
    ASK_LOCATION = "ASK_LOCATION"
    ASK_DISTRICT = "ASK_DISTRICT"
    ASK_STATE = "ASK_STATE"
    ASK_CITY = "ASK_CITY"
    ASK_ADDRESS = "ASK_ADDRESS"
    ASK_LANDMARK = "ASK_LANDMARK"
    ASK_PHOTO = "ASK_PHOTO"
    ASK_REQUIRED_FIELDS = "ASK_REQUIRED_FIELDS"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    SHOW_OFFICE = "SHOW_OFFICE"
    SHOW_SCHEME = "SHOW_SCHEME"
    CONFIRM_AND_FILE = "CONFIRM_AND_FILE"
    FILE_COMPLAINT = "FILE_COMPLAINT"
    TRACK_COMPLAINT = "TRACK_COMPLAINT"
    COMPLETE = "COMPLETE"
