# Generated by Django 5.2.15 on 2026-07-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('locations', '0002_district_is_deleted_district_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scheme Category',
                'verbose_name_plural': 'Scheme Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scheme_name', models.CharField(max_length=250, unique=True)),
                ('scheme_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for AI recommendation.')),
                ('official_website', models.URLField()),
                ('application_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='departments.department')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='locations.state')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='schemes.schemecategory')),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_name', models.CharField(max_length=150)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='schemes.governmentscheme')),
            ],
            options={
                'verbose_name': 'Required Document',
                'verbose_name_plural': 'Required Documents',
                'ordering': ['document_name'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'document_name'), name='unique_required_document')],
            },
        ),
    ]
