# Generated by Django 5.2.15 on 2026-07-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='helpline_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
