# Generated by Django 5.2.15 on 2026-08-15 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('complaints', '0002_complaintsupport'),
        ('departments', '0001_initial'),
        ('locations', '0002_district_is_deleted_district_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/resolutions/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_verified_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CivicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('ward_name', models.CharField(default='Ward Central', max_length=150)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=350000.0, max_digits=12)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed Cluster'), ('VOTED_FOR_FUNDING', 'Voted for Funding'), ('IN_EXECUTION', 'In Execution'), ('COMPLETED', 'Completed & Verified')], default='PROPOSED', max_length=30)),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='projects/resolutions/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.complaintcategory')),
                ('complaints', models.ManyToManyField(blank=True, related_name='civic_projects', to='complaints.complaint')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CivicProjectVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='complaints.civicproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_vote')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fiscal_year', models.CharField(default='2025-2026', max_length=20)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=2500000.0, max_digits=14)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='departments.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='locations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='locations.state')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'district', 'fiscal_year'), name='unique_dept_district_budget')],
            },
        ),
    ]
