# Generated by Django 5.2.15 on 2026-08-16 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_after_image_complaint_budget_allocated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='civicproject',
            name='resolution_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='verified_by',
            field=models.ManyToManyField(blank=True, related_name='verified_civic_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
