# Generated by Django 5.2.15 on 2026-08-16 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_civicproject_resolution_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='civicproject',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_civic_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
