# Generated by Django 5.2.15 on 2026-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_civicproject_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicproject',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='rejected_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/rejected_proofs/'),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='rejected_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
