# Generated by Django 5.2.15 on 2026-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_civicprojectresolutionproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicproject',
            name='priority_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
