# Generated by Django 5.2.15 on 2026-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_civicproject_priority_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_ngo_assisted',
            field=models.BooleanField(default=False, help_text='Filed by registered NGO on behalf of rural citizen'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ngo_name',
            field=models.CharField(blank=True, help_text='Name of assisting NGO', max_length=150),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_image',
            field=models.ImageField(blank=True, help_text='Citizen photo proof showing issue remains unresolved', null=True, upload_to='complaints/rejections/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Citizen rejection feedback when officer resolution is disputed'),
        ),
    ]
