# Generated by Django 5.2.15 on 2026-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_is_ngo_assisted_complaint_ngo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rural_citizen_name',
            field=models.CharField(blank=True, help_text='Name of rural citizen beneficiary', max_length=150),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rural_citizen_phone',
            field=models.CharField(blank=True, help_text='Mobile phone number of rural citizen beneficiary', max_length=15),
        ),
    ]
