# Generated by Django 5.2.15 on 2026-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_rural_citizen_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_ngo_assisted',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ngo_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rejection_image',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rural_citizen_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rural_citizen_phone',
        ),
        migrations.AddField(
            model_name='civicproject',
            name='csr_pledged_amount',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='csr_sponsor_name',
            field=models.CharField(blank=True, default='Tata Trusts & Local CSR Pool', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='is_csr_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='is_ngo_audited',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='ngo_audit_remarks',
            field=models.TextField(blank=True, default='Physical on-ground site inspection verified by certified NGO social auditor.', null=True),
        ),
        migrations.AddField(
            model_name='civicproject',
            name='ngo_auditor_name',
            field=models.CharField(blank=True, default='Jan Sahas Social Audit Team', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assisted_by_ngo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_assisted_filing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_ngo_audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ngo_audit_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ngo_auditor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
